general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 1000
}

background {
    monitor =
    path = ~/.wallpapers/lockscreen.png
    brightness = 0.8
    blur_size = 2
    blur_passes = 2
    contrast = 1.2
}

label {
    monitor =
    position = 0,200

    text = $TIME
    color = rgb(69, 133, 136)
    font_family = JetBrains Mono
    font_size = 100
}

label {
    monitor = 
    halign = left
    valign = top
    position = 40, -40

    color = rgb(228, 213, 173)
    text = $LAYOUT
    font_size = 25
    font_family = JetBrains Mono
}

input-field {
    monitor = 
    position = 0, -20
    size = 15%, 5%
    fade_on_empty = false

    outline_thickness = 3
    rounding = 0

    outer_color = rgb(214, 93, 14)
    inner_color = rgb(40, 40, 40)
    font_color = rgb(228, 213, 173)

    placeholder_text = Enter Password...
}
