general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
}
listener {
    timeout = 60
    on-timeout = brightnessctl -s set 5%
    on-resume = brightnessctl -r
}
listener {
    timeout = 150
    on-timeout = loginctl lock-session
}
listener {
    timeout = 300
    on-timeout = systemctl syspend
}
listener {
    timeout = 600
    on-timeout = systemctl hibernate
}
